### ISSUE TITLE
Re-implement RAM AtomDB in C++

### ISSUE THREAD

**Issue by andre-senna** [singnet/das#93]
### Pending:
- [ ] Atom mergers -> https://github.com/singnet/das/issues/136
- [ ] Logs -> https://github.com/singnet/das/issues/135

### Done:
- [x] Custom Attributes -> https://github.com/singnet/das-atom-db/issues/221
- [x] `.deb` package -> https://github.com/singnet/das-atom-db/issues/246
- [x] Sync Py-C++ -> https://github.com/singnet/das-atom-db/issues/247
- [x] Sync QE-New Atom DB -> https://github.com/singnet/das-query-engine/issues/354
- [x] _[Hot Improvement]_ Binary matrices cache -> https://github.com/singnet/das-atom-db/issues/256
- [X] Sync `das-serverless-functions` tests -> https://github.com/singnet/das-serverless-functions/issues/160

### Hotfixes (**all done**):
- https://github.com/singnet/das-atom-db/issues/231
- https://github.com/singnet/das-atom-db/issues/235
- https://github.com/singnet/das-atom-db/issues/238
- https://github.com/singnet/das-atom-db/issues/240
- https://github.com/singnet/das-atom-db/issues/260
